[profile.default]
src = "src"
out = "out"
libs = ["lib/openzeppelin-contracts"]
remappings = ["openzeppelin-contracts=lib/openzeppelin-contracts/contracts/"]

[profile.release]
optimizer = true
runs = 200